### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by EmilBlume** [hamishcampbell/silverstripe-securefiles#2]
After fresh install I got the following error:

Parse error: syntax error, unexpected T_CONSTANT_ENCAPSED_STRING in /home/encode/public_html/sandbox/securefiles/lang/de_DE.php on line 20

The written error was in line 17, after correcting from

$lang['de_DE']['SecureFiles']['NEVEREXPIRES'] =  'Niemals'';

to

$lang['de_DE']['SecureFiles']['NEVEREXPIRES'] =  'Niemals';

everything works fine.

**Comment by hamishcampbell** [comment]
Thanks
